### PR TITLE
New Updates & Improvements

### PR DESCRIPTION
**Pull request by Chainski**
- [x] Updated README
- [x] Improved ```ANTIVM``` check
- [x] Added ```AMSI``` Bypass 
- [x] Refactored the entire code & Reduced detection rate 

### Webcam screenshot is still functional but is downloaded on runtime due to 

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:PowerShell/EmpireGetScreenshot.A&threatId=-2147224978

### CODE REVIEW

**Comment by KDot227** [comment]
@Chainski Did you make the webcam grabbing that you added or did I, I honestly forgot.

**Comment by KDot227** [comment]
I'm also going to add back exe option and hopefully get rid of the python code needed. I THINK I found a way to access sql dbs in powershell but I haven't tested a lot yet.

**Comment by KDot227** [comment]
It's also going to require a LOT of code and I lowkey don't want the main.ps1 file flooded more than it already is but what can you do about it,

**Comment by KDot227** [comment]
Also, I understand the light obfuscation for the AMSI stuff but what if we just make our own powershell obf? Powershell has an open AST so we can easily parse things, I can show you some successful obfuscation and show you how easy it is to make but the only downside is that we would have to do it all in powershell.

**Comment by Chainski** [comment]
> It's also going to require a LOT of code and I lowkey don't want the main.ps1 file flooded more than it already is but what can you do about it,

 What you could do is make them download on runtime like it did with ```webcam.ps1```


> @Chainski Did you make the webcam grabbing that you added or did I, I honestly forgot.

check this line in [webcam.ps1](https://github.com/Chainski/PowerShell-Token-Grabber/blob/7666c0cee9ed82adbd25e988924b679bbcdaedde/webcam.ps1#L2)

**Comment by Chainski** [comment]
> Also, I understand the light obfuscation for the AMSI stuff but what if we just make our own powershell obf? Powershell has an open AST so we can easily parse things, I can show you some successful obfuscation and show you how easy it is to make but the only downside is that we would have to do it all in powershell.

I added the AMSI stuff due to https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:PowerShell/EmpireGetScreenshot.A&threatId=-2147224978

**Comment by KDot227** [comment]
> > Also, I understand the light obfuscation for the AMSI stuff but what if we just make our own powershell obf? Powershell has an open AST so we can easily parse things, I can show you some successful obfuscation and show you how easy it is to make but the only downside is that we would have to do it all in powershell.
> 
> I added the AMSI stuff due to the webcam function getting detected by https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:PowerShell/EmpireGetScreenshot.A&threatId=-2147224978

The AMSI stuff also acts for the python file too which is nice but AMSI bypasses can get detected very fast, what we CAN do is make the webcam grabbing optional therefore we only add the AMSI bypass when needed. If worse comes to worse I can compile the main.py file differently or make it in a different lang. I already have a working grabber that I made in nim, it's about 300kb but it does require a few dll's that need to be present in the same dir but the dll's are trusted (libcrypto, pcre, etc). It's your choice I'm cool with whatever.

**Comment by Chainski** [comment]
> > > Also, I understand the light obfuscation for the AMSI stuff but what if we just make our own powershell obf? Powershell has an open AST so we can easily parse things, I can show you some successful obfuscation and show you how easy it is to make but the only downside is that we would have to do it all in powershell.
> > 
> > 
> > I added the AMSI stuff due to the webcam function getting detected by https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:PowerShell/EmpireGetScreenshot.A&threatId=-2147224978
> 
> The AMSI stuff also acts for the python file too which is nice but AMSI bypasses can get detected very fast, what we CAN do is make the webcam grabbing optional therefore we only add the AMSI bypass when needed. If worse comes to worse I can compile the main.py file differently or make it in a different lang. I already have a working grabber that I made in nim, it's about 300kb but it does require a few dll's that need to be present in the same dir but the dll's are trusted (libcrypto, pcre, etc). It's your choice I'm cool with whatever.

They can get detected but we can always change code around to remove the detections. You can make it in a different lang especially ````nim, golang or rust```` since native executable can be loaded into memory using ```powershell``` without dropping files to disk which greatly reduce the detections but this may require alot of work.

**Comment by KDot227** [comment]
> > > > Also, I understand the light obfuscation for the AMSI stuff but what if we just make our own powershell obf? Powershell has an open AST so we can easily parse things, I can show you some successful obfuscation and show you how easy it is to make but the only downside is that we would have to do it all in powershell.
> > > 
> > > 
> > > I added the AMSI stuff due to the webcam function getting detected by https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:PowerShell/EmpireGetScreenshot.A&threatId=-2147224978
> > 
> > 
> > The AMSI stuff also acts for the python file too which is nice but AMSI bypasses can get detected very fast, what we CAN do is make the webcam grabbing optional therefore we only add the AMSI bypass when needed. If worse comes to worse I can compile the main.py file differently or make it in a different lang. I already have a working grabber that I made in nim, it's about 300kb but it does require a few dll's that need to be present in the same dir but the dll's are trusted (libcrypto, pcre, etc). It's your choice I'm cool with whatever.
> 
> They can get detected but we can always change code around to remove the detections. You can make it in a different lang especially `nim, golang or rust` since native executable can be loaded into memory using `powershell` without dropping files to disk which greatly reduce the detections but this may require alot of work.

now that you mention it the python exe might be able to run in memory too but since it's bascially self extracting I'm not too sure how it would work with that. I'll play around with it and see what I can do. I don't think nim would work for the dll reason I mentioned before but I'm down to make it in golang if you think it would be a good idea. I know a small amount but it's probably enough. Atleast golang doesn't requrie me to put everything in one file 🤣

**Pull request merged**
